plugins {
    id 'java-gradle-plugin'
    id 'idea'
    id 'eclipse'
    id 'maven-publish'
    alias libs.plugins.gradleutils
    alias libs.plugins.plugin.publish
}

final projectDisplayName = 'Gradle Github Packages Plugin'
description = 'Gradle plugin for adding maven repos on Github Packages in one line'
group = 'me.jonathing.gradle'
version = gitversion.tagOffset

println "Version: $version"

java.toolchain.languageVersion = JavaLanguageVersion.of 8

dependencies {
    compileOnly libs.gradle
    compileOnly libs.nulls
}

changelog {
    from '2.0'
    publishAll = false
}

gradlePlugin {
    website.set gitversion.url
    vcsUrl.set gitversion.url + '.git'

    plugins.register('github-packages') {
        id = 'me.jonathing.gradle.github-packages'
        implementationClass = 'me.jonathing.gradle.gpr.GithubPackagesPlugin'
        displayName = projectDisplayName
        description = project.description
        tags = ['github', 'github-packages', 'dependency', 'maven', 'repository']
    }
}

publishing {
    publications.register('pluginMaven', MavenPublication) {
        artifactId = project.name

        pom { pom ->
            name = projectDisplayName
            description = project.description

            // TODO [GHPackages] Re-enable in GradleUtils 3.0
            //gradleutils.pom.setGitHubDetails pom

            licenses {
                license gradleutils.pom.licenses.MIT
            }

            developers {
                developer gradleutils.pom.developers.Jonathing
            }
        }
    }

    repositories {
        maven {
            name = 'ModdingLegacyMaven'
            url = 'https://maven.moddinglegacy.com/repository/modding-legacy/'
            credentials {
                username = providers.gradleProperty('mlm.user').orElse(providers.environmentVariable('ML_USERNAME')).orNull
                password = providers.gradleProperty('mlm.key').orElse(providers.environmentVariable('ML_TOKEN')).orNull
            }
        }
    }
}

idea.module { downloadSources = downloadJavadoc = true }
